server:
  http_addr: ":9081"

rate_limit:
  auth_rps: 5
  auth_burst: 10

mysql:
  dsn: "blog:blog123@tcp(127.0.0.1:3306)/blog_demo?parseTime=true&loc=Local"

redis:
  addr: "127.0.0.1:6379"
  password: ""
  db: 0

jwt:
  secret: "please-change-this-local-secret"
  expire_hours: 24
