// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package handler

import (
	"net/http"

	"github.com/zzxrepository/gocode-examples/go/01-go-zero-demo/gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/auth/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/auth/register",
				Handler: RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/posts",
				Handler: ListPostsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/posts",
				Handler: CreatePostHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/posts/:id",
				Handler: GetPostHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/posts/:id",
				Handler: UpdatePostHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/posts/:id",
				Handler: DeletePostHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
