// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type IDRequest struct {
	ID int64 `path:"id"`
}

type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type PostListResponse struct {
	Posts []PostResponse `json:"posts"`
}

type PostRequest struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type PostResponse struct {
	ID      int64  `json:"id"`
	UserID  int64  `json:"userId"`
	Title   string `json:"title"`
	Content string `json:"content"`
}

type RegisterRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type TokenResponse struct {
	Token  string `json:"token"`
	UserID int64  `json:"userId"`
}

type UpdateRequest struct {
	ID      int64  `path:"id"`
	Title   string `json:"title"`
	Content string `json:"content"`
}
