// 枚举校验示例。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v7.35.1
// source: proto/enum.proto

package proto

import (
	_ "github.com/mwitkow/go-proto-validators"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Action 定义三个允许的枚举值。
type Action int32

const (
	Action_ALLOW Action = 0
	Action_DENY  Action = 1
	Action_CHILL Action = 2
)

// Enum value maps for Action.
var (
	Action_name = map[int32]string{
		0: "ALLOW",
		1: "DENY",
		2: "CHILL",
	}
	Action_value = map[string]int32{
		"ALLOW": 0,
		"DENY":  1,
		"CHILL": 2,
	}
)

func (x Action) Enum() *Action {
	p := new(Action)
	*p = x
	return p
}

func (x Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_enum_proto_enumTypes[0].Descriptor()
}

func (Action) Type() protoreflect.EnumType {
	return &file_proto_enum_proto_enumTypes[0]
}

func (x Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action.Descriptor instead.
func (Action) EnumDescriptor() ([]byte, []int) {
	return file_proto_enum_proto_rawDescGZIP(), []int{0}
}

// SomeMsg 演示如何校验枚举字段。
type SomeMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// is_in_enum 表示 do 必须是 Action 枚举中定义过的值。
	Do Action `protobuf:"varint,1,opt,name=do,proto3,enum=proto.Action" json:"do,omitempty"`
}

func (x *SomeMsg) Reset() {
	*x = SomeMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_enum_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SomeMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SomeMsg) ProtoMessage() {}

func (x *SomeMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_enum_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SomeMsg.ProtoReflect.Descriptor instead.
func (*SomeMsg) Descriptor() ([]byte, []int) {
	return file_proto_enum_proto_rawDescGZIP(), []int{0}
}

func (x *SomeMsg) GetDo() Action {
	if x != nil {
		return x.Do
	}
	return Action_ALLOW
}

var File_proto_enum_proto protoreflect.FileDescriptor

var file_proto_enum_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0f, 0x76, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x31, 0x0a, 0x07, 0x53, 0x6f,
	0x6d, 0x65, 0x4d, 0x73, 0x67, 0x12, 0x26, 0x0a, 0x02, 0x64, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x42, 0x07, 0xe2, 0xdf, 0x1f, 0x03, 0x88, 0x01, 0x01, 0x52, 0x02, 0x64, 0x6f, 0x2a, 0x28, 0x0a,
	0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x4c, 0x4c, 0x4f, 0x57,
	0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x45, 0x4e, 0x59, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05,
	0x43, 0x48, 0x49, 0x4c, 0x4c, 0x10, 0x02, 0x42, 0x26, 0x5a, 0x24, 0x67, 0x6f, 0x2d, 0x67, 0x72,
	0x70, 0x63, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x6f, 0x72, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_enum_proto_rawDescOnce sync.Once
	file_proto_enum_proto_rawDescData = file_proto_enum_proto_rawDesc
)

func file_proto_enum_proto_rawDescGZIP() []byte {
	file_proto_enum_proto_rawDescOnce.Do(func() {
		file_proto_enum_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_enum_proto_rawDescData)
	})
	return file_proto_enum_proto_rawDescData
}

var file_proto_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_enum_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_enum_proto_goTypes = []any{
	(Action)(0),     // 0: proto.Action
	(*SomeMsg)(nil), // 1: proto.SomeMsg
}
var file_proto_enum_proto_depIdxs = []int32{
	0, // 0: proto.SomeMsg.do:type_name -> proto.Action
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_enum_proto_init() }
func file_proto_enum_proto_init() {
	if File_proto_enum_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_enum_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SomeMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_enum_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_enum_proto_goTypes,
		DependencyIndexes: file_proto_enum_proto_depIdxs,
		EnumInfos:         file_proto_enum_proto_enumTypes,
		MessageInfos:      file_proto_enum_proto_msgTypes,
	}.Build()
	File_proto_enum_proto = out.File
	file_proto_enum_proto_rawDesc = nil
	file_proto_enum_proto_goTypes = nil
	file_proto_enum_proto_depIdxs = nil
}
