// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: post.proto

package post

import (
	"context"

	pb_postpb "github.com/zzxrepository/gocode-examples/go/01-go-zero-demo/post/pb/github.com/zzxrepository/gocode-examples/go/01-go-zero-demo/post/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateRequest = pb_postpb.CreateRequest
	DeleteRequest = pb_postpb.DeleteRequest
	Empty         = pb_postpb.Empty
	ListRequest   = pb_postpb.ListRequest
	PostIDRequest = pb_postpb.PostIDRequest
	PostListReply = pb_postpb.PostListReply
	PostReply     = pb_postpb.PostReply
	UpdateRequest = pb_postpb.UpdateRequest

	Post interface {
		List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*PostListReply, error)
		Get(ctx context.Context, in *PostIDRequest, opts ...grpc.CallOption) (*PostReply, error)
		Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*PostReply, error)
		Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*PostReply, error)
		Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*Empty, error)
	}

	defaultPost struct {
		cli zrpc.Client
	}
)

func NewPost(cli zrpc.Client) Post {
	return &defaultPost{
		cli: cli,
	}
}

func (m *defaultPost) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*PostListReply, error) {
	client := pb_postpb.NewPostClient(m.cli.Conn())
	return client.List(ctx, in, opts...)
}

func (m *defaultPost) Get(ctx context.Context, in *PostIDRequest, opts ...grpc.CallOption) (*PostReply, error) {
	client := pb_postpb.NewPostClient(m.cli.Conn())
	return client.Get(ctx, in, opts...)
}

func (m *defaultPost) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*PostReply, error) {
	client := pb_postpb.NewPostClient(m.cli.Conn())
	return client.Create(ctx, in, opts...)
}

func (m *defaultPost) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*PostReply, error) {
	client := pb_postpb.NewPostClient(m.cli.Conn())
	return client.Update(ctx, in, opts...)
}

func (m *defaultPost) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := pb_postpb.NewPostClient(m.cli.Conn())
	return client.Delete(ctx, in, opts...)
}
