// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: post.proto

package server

import (
	"context"

	"github.com/zzxrepository/gocode-examples/go/01-go-zero-demo/post/internal/logic"
	"github.com/zzxrepository/gocode-examples/go/01-go-zero-demo/post/internal/svc"
	pb_postpb "github.com/zzxrepository/gocode-examples/go/01-go-zero-demo/post/pb/github.com/zzxrepository/gocode-examples/go/01-go-zero-demo/post/pb"
)

type PostServer struct {
	svcCtx *svc.ServiceContext
	pb_postpb.UnimplementedPostServer
}

func NewPostServer(svcCtx *svc.ServiceContext) *PostServer {
	return &PostServer{
		svcCtx: svcCtx,
	}
}

func (s *PostServer) List(ctx context.Context, in *pb_postpb.ListRequest) (*pb_postpb.PostListReply, error) {
	l := logic.NewListLogic(ctx, s.svcCtx)
	return l.List(in)
}

func (s *PostServer) Get(ctx context.Context, in *pb_postpb.PostIDRequest) (*pb_postpb.PostReply, error) {
	l := logic.NewGetLogic(ctx, s.svcCtx)
	return l.Get(in)
}

func (s *PostServer) Create(ctx context.Context, in *pb_postpb.CreateRequest) (*pb_postpb.PostReply, error) {
	l := logic.NewCreateLogic(ctx, s.svcCtx)
	return l.Create(in)
}

func (s *PostServer) Update(ctx context.Context, in *pb_postpb.UpdateRequest) (*pb_postpb.PostReply, error) {
	l := logic.NewUpdateLogic(ctx, s.svcCtx)
	return l.Update(in)
}

func (s *PostServer) Delete(ctx context.Context, in *pb_postpb.DeleteRequest) (*pb_postpb.Empty, error) {
	l := logic.NewDeleteLogic(ctx, s.svcCtx)
	return l.Delete(in)
}
