// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: user.proto

package user

import (
	"context"

	pb_userpb "github.com/zzxrepository/gocode-examples/go/01-go-zero-demo/user/pb/github.com/zzxrepository/gocode-examples/go/01-go-zero-demo/user/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	LoginRequest    = pb_userpb.LoginRequest
	RegisterRequest = pb_userpb.RegisterRequest
	TokenReply      = pb_userpb.TokenReply
	TokenRequest    = pb_userpb.TokenRequest
	UserReply       = pb_userpb.UserReply

	User interface {
		Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*UserReply, error)
		Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*TokenReply, error)
		ValidateToken(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*UserReply, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*UserReply, error) {
	client := pb_userpb.NewUserClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

func (m *defaultUser) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*TokenReply, error) {
	client := pb_userpb.NewUserClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultUser) ValidateToken(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*UserReply, error) {
	client := pb_userpb.NewUserClient(m.cli.Conn())
	return client.ValidateToken(ctx, in, opts...)
}
