// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: user.proto

package server

import (
	"context"

	"github.com/zzxrepository/gocode-examples/go/01-go-zero-demo/user/internal/logic"
	"github.com/zzxrepository/gocode-examples/go/01-go-zero-demo/user/internal/svc"
	pb_userpb "github.com/zzxrepository/gocode-examples/go/01-go-zero-demo/user/pb/github.com/zzxrepository/gocode-examples/go/01-go-zero-demo/user/pb"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	pb_userpb.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Register(ctx context.Context, in *pb_userpb.RegisterRequest) (*pb_userpb.UserReply, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserServer) Login(ctx context.Context, in *pb_userpb.LoginRequest) (*pb_userpb.TokenReply, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserServer) ValidateToken(ctx context.Context, in *pb_userpb.TokenRequest) (*pb_userpb.UserReply, error) {
	l := logic.NewValidateTokenLogic(ctx, s.svcCtx)
	return l.ValidateToken(in)
}
